### ISSUE TITLE
special characters in events

### ISSUE THREAD

**Issue by alexmat** [evuraan/edotool#1]
```
edotool -e "${varwithspecialchars}"
```

This command will only print until it hits a special character like - then terminate. Is there a way to be able to pass strings containing special characters to edotool?

**Comment by evuraan** [comment]
@alexmat:  Please try with ver `3.x` I pushed recently. It has a lot more features, you may be able to use a `.skit` file to get what you desire. Or, chain your events using the `-e` option.  Either way, please keep me posted! 

Thanks!
